export interface Product {
  id: string;
  name: string;
  category: "3d-printed" | "laser-engraved" | "electronics";
  subcategory: string;
  price: number;
  originalPrice?: number;
  currency: string;
  description: string;
  longDescription: string;
  images: string[];
  thumbnail: string;
  stock: number;
  isInStock: boolean;
  isFeatured: boolean;
  isNew: boolean;
  rating: number;
  reviewCount: number;
  specifications: Record<string, string>;
  tags: string[];
  relatedProducts: string[];
}

export interface Category {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: string;
  image: string;
  productCount: number;
}

export const categories: Category[] = [
  {
    id: "3d-printed",
    name: "3D Printed Items",
    slug: "3d-printed",
    description: "Custom 3D printed products made in our lab",
    icon: "FiPrinter",
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=600",
    productCount: 25,
  },
  {
    id: "laser-engraved",
    name: "Laser Engraved Items",
    slug: "laser-engraved",
    description: "Personalized laser engraved products",
    icon: "FiZap",
    image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=600",
    productCount: 18,
  },
  {
    id: "electronics",
    name: "Basic Electronics",
    slug: "electronics",
    description: "Essential electronics components for robotics",
    icon: "FiCpu",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=600",
    productCount: 32,
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Custom 3D Printed Robot Arm Bracket",
    category: "3d-printed",
    subcategory: "Robot Parts",
    price: 45.99,
    originalPrice: 59.99,
    currency: "USD",
    description: "High-quality 3D printed bracket for robot arm assembly. Made with premium PLA material, designed for durability and precision. Perfect for robotics projects and prototypes.",
    longDescription: "Our 3D printed robot arm bracket is meticulously designed for robotics enthusiasts and professionals. This bracket is manufactured using advanced FDM printing technology with premium PLA material, ensuring exceptional strength and dimensional accuracy. Features include precise mounting holes, reinforced joints, and smooth surface finish. Compatible with standard servo motors and mounting hardware. Ideal for educational projects, prototyping, and custom robot builds.",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    stock: 25,
    isInStock: true,
    isFeatured: true,
    isNew: true,
    rating: 4.5,
    reviewCount: 12,
    specifications: {
      material: "PLA",
      color: "Black",
      dimensions: "50mm x 40mm x 20mm",
      weight: "15g",
      printTime: "2.5 hours",
      compatibility: "Standard servo motors",
    },
    tags: ["robot", "bracket", "3d-print", "hardware"],
    relatedProducts: ["2", "5", "8"],
  },
  {
    id: "2",
    name: "Personalized Laser Engraved Nameplate",
    category: "laser-engraved",
    subcategory: "Personalized Items",
    price: 29.99,
    currency: "USD",
    description: "Custom laser engraved nameplate made from premium wood. Perfect for desks, offices, or as a gift. Multiple sizes available.",
    longDescription: "Create a personalized touch with our laser engraved nameplates. Each nameplate is crafted from high-quality hardwood and engraved using precision laser technology. The result is a professional, elegant finish that will last for years. Customize with any name or text up to 25 characters. Available in multiple wood types: Oak, Walnut, and Maple. Comes with pre-drilled mounting holes for easy installation.",
    images: [
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400",
    stock: 50,
    isInStock: true,
    isFeatured: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 28,
    specifications: {
      material: "Premium Hardwood",
      sizes: "Small (4x1 inch), Medium (6x1.5 inch), Large (8x2 inch)",
      engravingDepth: "0.5mm",
      customization: "Text up to 25 characters",
      finish: "Natural wood with clear coat",
      mounting: "Pre-drilled holes included",
    },
    tags: ["personalized", "gift", "office", "laser"],
    relatedProducts: ["3", "6", "9"],
  },
  {
    id: "3",
    name: "Arduino Starter Kit - Robotics Edition",
    category: "electronics",
    subcategory: "Microcontrollers",
    price: 79.99,
    originalPrice: 99.99,
    currency: "USD",
    description: "Complete Arduino starter kit perfect for robotics projects. Includes Arduino Uno, breadboard, sensors, motors, and detailed project guide.",
    longDescription: "Jumpstart your robotics journey with our comprehensive Arduino Starter Kit. This kit includes everything you need to build exciting robotics projects. Contents: Arduino Uno R3 board, breadboard, jumper wires, LEDs, resistors, potentiometer, servos, DC motors, ultrasonic sensor, IR sensor, temperature sensor, and a 50+ page project guide. Perfect for beginners and intermediate makers. All components are tested and ready to use. Start building your first robot in under 30 minutes!",
    images: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=400",
    stock: 15,
    isInStock: true,
    isFeatured: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 45,
    specifications: {
      board: "Arduino Uno R3",
      voltage: "5V",
      current: "40mA (standby), 50mA (active)",
      microcontroller: "ATmega328P",
      digitalPins: "14",
      analogPins: "6",
      includedComponents: "Breadboard, sensors, motors, LEDs, resistors, wires",
      compatibility: "Arduino IDE, Scratch for Arduino",
    },
    tags: ["arduino", "starter-kit", "robotics", "electronics"],
    relatedProducts: ["4", "7", "10"],
  },
  {
    id: "4",
    name: "3D Printed Phone Stand - Adjustable Angle",
    category: "3d-printed",
    subcategory: "Accessories",
    price: 19.99,
    currency: "USD",
    description: "Ergonomic phone stand with adjustable viewing angles. Compatible with all smartphone sizes.",
    longDescription: "This sleek phone stand is 3D printed using durable PETG material for long-lasting use. Features adjustable viewing angles from 45° to 90°, cable management slot, and non-slip base. Perfect for desk setups, video calls, and hands-free viewing. Compact design that fits in your bag.",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    stock: 40,
    isInStock: true,
    isFeatured: false,
    isNew: true,
    rating: 4.6,
    reviewCount: 34,
    specifications: {
      material: "PETG",
      color: "Black, White, Red",
      dimensions: "80mm x 60mm x 45mm",
      weight: "30g",
      compatibility: "All smartphone sizes",
      printTime: "1.5 hours",
    },
    tags: ["phone", "stand", "accessory", "desk"],
    relatedProducts: ["1", "5", "11"],
  },
  {
    id: "5",
    name: "Laser Engraved Wooden Keychain",
    category: "laser-engraved",
    subcategory: "Accessories",
    price: 12.99,
    currency: "USD",
    description: "Personalized wooden keychain with laser engraved design. Perfect as a gift or personal accessory.",
    longDescription: "Crafted from premium birch wood, this keychain features precise laser engraving that won't fade over time. Available in round or square shapes with custom text or simple designs. Includes a metal key ring. Makes an excellent gift for friends, colleagues, or yourself.",
    images: [
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400",
    stock: 75,
    isInStock: true,
    isFeatured: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 52,
    specifications: {
      material: "Birch Wood",
      size: "40mm diameter (round) or 40x40mm (square)",
      engravingDepth: "0.3mm",
      customization: "Text or simple design",
      finish: "Natural wood with light varnish",
      keyRing: "Included metal ring",
    },
    tags: ["keychain", "personalized", "gift", "wood"],
    relatedProducts: ["2", "6", "12"],
  },
  {
    id: "6",
    name: "Ultrasonic Distance Sensor HC-SR04",
    category: "electronics",
    subcategory: "Sensors",
    price: 8.99,
    currency: "USD",
    description: "High-precision ultrasonic sensor for distance measurement. Perfect for robotics and automation projects.",
    longDescription: "The HC-SR04 ultrasonic sensor provides accurate distance measurement from 2cm to 400cm with 3mm precision. Features 4 pins (VCC, Trig, Echo, GND) for easy Arduino integration. Ideal for obstacle avoidance robots, parking sensors, and proximity detection systems. Comes with mounting holes for secure installation.",
    images: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=400",
    stock: 60,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.5,
    reviewCount: 89,
    specifications: {
      range: "2cm - 400cm",
      accuracy: "3mm",
      voltage: "5V",
      current: "15mA",
      frequency: "40kHz",
      interface: "4-pin (VCC, Trig, Echo, GND)",
      compatibility: "Arduino, Raspberry Pi, ESP32",
    },
    tags: ["sensor", "ultrasonic", "robotics", "distance"],
    relatedProducts: ["3", "7", "13"],
  },
  {
    id: "7",
    name: "3D Printed Cable Organizer Box",
    category: "3d-printed",
    subcategory: "Organizers",
    price: 24.99,
    currency: "USD",
    description: "Custom cable management box with lid. Keep your workspace organized and clutter-free.",
    longDescription: "This cable organizer box features a snap-fit lid design and multiple cable routing holes. Made from durable PLA material with smooth surface finish. Perfect for organizing cables, adapters, and small accessories on your desk. Available in multiple colors to match your setup.",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    stock: 30,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.4,
    reviewCount: 21,
    specifications: {
      material: "PLA",
      dimensions: "150mm x 100mm x 50mm",
      weight: "80g",
      color: "Black, White, Gray",
      printTime: "3 hours",
      features: "Snap-fit lid, cable routing holes",
    },
    tags: ["organizer", "cable", "desk", "storage"],
    relatedProducts: ["4", "8", "14"],
  },
  {
    id: "8",
    name: "Laser Engraved Wooden Coasters Set (4pc)",
    category: "laser-engraved",
    subcategory: "Home Decor",
    price: 34.99,
    currency: "USD",
    description: "Set of 4 premium wooden coasters with custom laser engraved designs. Protect your furniture in style.",
    longDescription: "This beautiful set includes 4 premium hardwood coasters, each featuring intricate laser engraved patterns. The coasters are sealed with a water-resistant finish to protect your furniture. Designs range from geometric patterns to nature-inspired motifs. Perfect for home, office, or as a gift.",
    images: [
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400",
    stock: 35,
    isInStock: true,
    isFeatured: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 67,
    specifications: {
      material: "Premium Hardwood",
      quantity: "4 coasters",
      size: "95mm diameter each",
      thickness: "6mm",
      finish: "Water-resistant sealant",
      design: "Custom laser engraved patterns",
    },
    tags: ["coasters", "home", "decor", "wood"],
    relatedProducts: ["2", "5", "15"],
  },
  {
    id: "9",
    name: "SG90 Micro Servo Motor (Pack of 2)",
    category: "electronics",
    subcategory: "Motors",
    price: 14.99,
    currency: "USD",
    description: "High-quality micro servo motors perfect for robotics projects. Smooth operation and precise control.",
    longDescription: "The SG90 micro servo motor is a standard servo motor with 180° rotation range. Ideal for robot joints, pan-tilt cameras, and small automation projects. Each pack includes 2 servo motors with mounting hardware and servo horns. Compatible with Arduino, Raspberry Pi, and most microcontrollers.",
    images: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=400",
    stock: 45,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.6,
    reviewCount: 112,
    specifications: {
      voltage: "4.8V - 6V",
      current: "100mA (idle), 500mA (active)",
      torque: "1.8kg/cm @ 4.8V",
      speed: "0.1s/60° @ 4.8V",
      rotation: "180°",
      size: "23mm x 12.5mm x 29mm",
      weight: "9g",
    },
    tags: ["servo", "motor", "robotics", "actuator"],
    relatedProducts: ["3", "6", "16"],
  },
  {
    id: "10",
    name: "3D Printed Robot Chassis Base Plate",
    category: "3d-printed",
    subcategory: "Robot Parts",
    price: 39.99,
    currency: "USD",
    description: "Strong and lightweight chassis base plate for small to medium robots. Pre-drilled mounting holes included.",
    longDescription: "This robust chassis base plate is designed for educational and hobby robotics projects. Features precise mounting holes for motors, sensors, and electronics. Made from reinforced PLA for durability. Compatible with common wheel and motor sizes. Perfect foundation for your next robot build.",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    stock: 20,
    isInStock: true,
    isFeatured: true,
    isNew: false,
    rating: 4.5,
    reviewCount: 43,
    specifications: {
      material: "Reinforced PLA",
      dimensions: "200mm x 150mm x 5mm",
      weight: "120g",
      color: "Black",
      printTime: "4 hours",
      mountingHoles: "M3 standard",
    },
    tags: ["robot", "chassis", "base", "platform"],
    relatedProducts: ["1", "11", "17"],
  },
  {
    id: "11",
    name: "Laser Engraved Custom Sign - Home/Office",
    category: "laser-engraved",
    subcategory: "Signs",
    price: 49.99,
    currency: "USD",
    description: "Custom laser engraved wooden sign for home or office. Multiple sizes and design options available.",
    longDescription: "Create a personalized wooden sign with your custom text or design. Made from premium plywood with professional laser engraving. Perfect for room signs, business names, inspirational quotes, or decorative purposes. Available in multiple sizes and finishes. Mounting hardware included.",
    images: [
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400",
    stock: 25,
    isInStock: true,
    isFeatured: false,
    isNew: true,
    rating: 4.8,
    reviewCount: 38,
    specifications: {
      material: "Premium Plywood",
      sizes: "Small (15x10cm), Medium (25x15cm), Large (35x20cm)",
      thickness: "6mm",
      finish: "Natural or stained",
      mounting: "Hardware included",
      customization: "Custom text/design",
    },
    tags: ["sign", "custom", "home", "office", "decor"],
    relatedProducts: ["2", "8", "18"],
  },
  {
    id: "12",
    name: "Breadboard Jumper Wires Pack (65pc)",
    category: "electronics",
    subcategory: "Components",
    price: 9.99,
    currency: "USD",
    description: "High-quality jumper wires in multiple lengths. Essential for prototyping and electronics projects.",
    longDescription: "This comprehensive jumper wire pack includes 65 wires in various lengths (10cm, 15cm, 20cm, 30cm) and colors for easy circuit organization. Made with quality materials for reliable connections. Perfect for Arduino, Raspberry Pi, and breadboard projects. Colors help organize your circuits visually.",
    images: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=400",
    stock: 100,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.7,
    reviewCount: 156,
    specifications: {
      quantity: "65 wires",
      lengths: "10cm, 15cm, 20cm, 30cm",
      colors: "Multiple colors",
      connector: "Male to male",
      gauge: "22 AWG",
      compatibility: "Breadboards, Arduino, Raspberry Pi",
    },
    tags: ["wires", "jumper", "breadboard", "prototyping"],
    relatedProducts: ["3", "13", "19"],
  },
  {
    id: "13",
    name: "3D Printed Headphone Stand",
    category: "3d-printed",
    subcategory: "Accessories",
    price: 22.99,
    currency: "USD",
    description: "Stylish headphone stand with cable management. Keeps your desk organized and headphones safe.",
    longDescription: "This elegant headphone stand is designed to hold any over-ear or on-ear headphones securely. Features a cable management channel to keep wires organized. Compact base ensures stability. Available in multiple colors to match your setup. Made from durable PETG material.",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    stock: 35,
    isInStock: true,
    isFeatured: false,
    isNew: true,
    rating: 4.6,
    reviewCount: 29,
    specifications: {
      material: "PETG",
      dimensions: "150mm x 150mm x 300mm",
      weight: "150g",
      color: "Black, White, Red",
      printTime: "2.5 hours",
      features: "Cable management channel",
    },
    tags: ["headphone", "stand", "desk", "accessory"],
    relatedProducts: ["4", "7", "20"],
  },
  {
    id: "14",
    name: "Laser Engraved Wooden Box - Small",
    category: "laser-engraved",
    subcategory: "Storage",
    price: 39.99,
    currency: "USD",
    description: "Beautiful handcrafted wooden box with laser engraved lid. Perfect for storing small items or as a gift box.",
    longDescription: "This elegant wooden box features a hinged lid with custom laser engraving. Crafted from premium hardwood with smooth interior and exterior finishes. Perfect for jewelry, small electronics, keepsakes, or as an elegant gift box. Custom engraving available for personalization.",
    images: [
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400",
    stock: 28,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.9,
    reviewCount: 41,
    specifications: {
      material: "Premium Hardwood",
      dimensions: "150mm x 100mm x 60mm",
      finish: "Smooth sanded and varnished",
      lid: "Hinged with laser engraving",
      customization: "Custom text/design on lid",
      interior: "Felt-lined (optional)",
    },
    tags: ["box", "storage", "wood", "gift"],
    relatedProducts: ["5", "11", "21"],
  },
  {
    id: "15",
    name: "DC Motor with Encoder (12V)",
    category: "electronics",
    subcategory: "Motors",
    price: 24.99,
    currency: "USD",
    description: "High-quality DC motor with built-in encoder for precise speed and position control. Perfect for robotics.",
    longDescription: "This 12V DC motor features a built-in quadrature encoder providing 390 pulses per revolution. Ideal for wheeled robots, conveyor systems, and precision automation projects. Includes mounting brackets and connector wires. Compatible with motor drivers like L298N and TB6612FNG.",
    images: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=400",
    stock: 32,
    isInStock: true,
    isFeatured: false,
    isNew: true,
    rating: 4.5,
    reviewCount: 78,
    specifications: {
      voltage: "12V DC",
      current: "100mA (no load), 500mA (rated)",
      speed: "200 RPM @ 12V",
      encoder: "390 pulses/revolution",
      torque: "0.15 Nm",
      size: "42mm diameter x 66mm length",
    },
    tags: ["motor", "dc", "encoder", "robotics"],
    relatedProducts: ["9", "16", "22"],
  },
  {
    id: "16",
    name: "3D Printed Robot Gripper Kit",
    category: "3d-printed",
    subcategory: "Robot Parts",
    price: 54.99,
    currency: "USD",
    description: "Complete 3D printed gripper kit with servo motor compatibility. Build your own robot hand!",
    longDescription: "This comprehensive gripper kit includes all 3D printed parts needed to assemble a functional robot gripper. Designed to work with standard SG90 servo motors. Features smooth finger movement, adjustable grip force, and compatibility with various robot arms. Assembly instructions included.",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    stock: 18,
    isInStock: true,
    isFeatured: true,
    isNew: true,
    rating: 4.7,
    reviewCount: 56,
    specifications: {
      material: "PLA+",
      parts: "Complete assembly kit",
      servoCompatibility: "SG90 or similar",
      gripWidth: "0-50mm adjustable",
      weight: "45g (without servo)",
      printTime: "5 hours total",
      includes: "Hardware and assembly guide",
    },
    tags: ["gripper", "robot", "servo", "kit"],
    relatedProducts: ["1", "9", "10"],
  },
  {
    id: "17",
    name: "Laser Engraved Acrylic Keychain (Clear)",
    category: "laser-engraved",
    subcategory: "Accessories",
    price: 15.99,
    currency: "USD",
    description: "Crystal clear acrylic keychain with precise laser engraving. Modern and elegant design.",
    longDescription: "Made from premium clear acrylic, this keychain features crisp laser engraving that creates a frosted effect. The transparent material allows for creative designs that catch the light beautifully. Available in various shapes and sizes. Perfect for modern, minimalist aesthetic.",
    images: [
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400",
    stock: 42,
    isInStock: true,
    isFeatured: false,
    isNew: true,
    rating: 4.6,
    reviewCount: 33,
    specifications: {
      material: "Clear Acrylic",
      thickness: "3mm",
      sizes: "40mm, 50mm, 60mm",
      finish: "Frosted laser engraving",
      keyRing: "Included",
      customization: "Custom text or design",
    },
    tags: ["acrylic", "keychain", "modern", "clear"],
    relatedProducts: ["5", "18", "23"],
  },
  {
    id: "18",
    name: "IR Obstacle Sensor Module",
    category: "electronics",
    subcategory: "Sensors",
    price: 6.99,
    currency: "USD",
    description: "Infrared obstacle detection sensor with adjustable sensitivity. Easy to integrate with Arduino.",
    longDescription: "This IR obstacle sensor module detects objects within 2-30cm range using infrared reflection. Features adjustable sensitivity via potentiometer, digital output, and LED indicators. Perfect for line-following robots, obstacle avoidance, and proximity detection. 3-pin interface makes integration simple.",
    images: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=400",
    stock: 85,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.4,
    reviewCount: 124,
    specifications: {
      range: "2-30cm",
      voltage: "3.3V - 5V",
      current: "20mA",
      output: "Digital (HIGH/LOW)",
      sensitivity: "Adjustable potentiometer",
      interface: "3-pin (VCC, GND, OUT)",
      compatibility: "Arduino, Raspberry Pi, ESP32",
    },
    tags: ["sensor", "ir", "obstacle", "detection"],
    relatedProducts: ["6", "19", "24"],
  },
  {
    id: "19",
    name: "3D Printed Desk Organizer Set",
    category: "3d-printed",
    subcategory: "Organizers",
    price: 44.99,
    currency: "USD",
    description: "Complete desk organizer set with compartments for pens, phones, and accessories. Modular design.",
    longDescription: "This modular desk organizer set includes a main tray with multiple compartments, a phone/tablet stand, pen holders, and small parts storage. All pieces work together or can be used independently. Made from durable PLA with smooth finish. Keep your workspace clean and organized.",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    stock: 27,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.5,
    reviewCount: 38,
    specifications: {
      material: "PLA",
      pieces: "5-piece set",
      dimensions: "Main tray: 200mm x 150mm",
      color: "Black, White, Gray",
      printTime: "6 hours total",
      features: "Modular, stackable design",
    },
    tags: ["organizer", "desk", "storage", "modular"],
    relatedProducts: ["4", "7", "13"],
  },
  {
    id: "20",
    name: "Laser Engraved Metal Business Card Case",
    category: "laser-engraved",
    subcategory: "Accessories",
    price: 29.99,
    currency: "USD",
    description: "Premium aluminum business card case with laser engraved logo or text. Professional and sleek.",
    longDescription: "Crafted from brushed aluminum, this business card case features precise laser engraving for a professional finish. Holds up to 50 standard business cards. Smooth sliding mechanism for easy access. Custom engraving available for company logos or personal text. Perfect for networking and professional settings.",
    images: [
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400",
    stock: 36,
    isInStock: true,
    isFeatured: false,
    isNew: true,
    rating: 4.8,
    reviewCount: 47,
    specifications: {
      material: "Brushed Aluminum",
      capacity: "Up to 50 cards",
      dimensions: "90mm x 60mm x 15mm",
      finish: "Brushed with laser engraving",
      mechanism: "Sliding lid",
      customization: "Logo or text engraving",
    },
    tags: ["business", "card", "case", "aluminum", "professional"],
    relatedProducts: ["2", "11", "17"],
  },
  {
    id: "21",
    name: "Resistor Kit - Assorted Values (500pc)",
    category: "electronics",
    subcategory: "Components",
    price: 12.99,
    currency: "USD",
    description: "Comprehensive resistor kit with 500 pieces covering common values. Essential for electronics projects.",
    longDescription: "This complete resistor kit includes 500 resistors covering the most commonly used values from 10Ω to 1MΩ. Resistors are color-coded for easy identification and come organized in labeled compartments. Perfect for prototyping, educational projects, and repairs. All resistors are 1/4W, 5% tolerance.",
    images: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=400",
    stock: 120,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.6,
    reviewCount: 203,
    specifications: {
      quantity: "500 pieces",
      values: "10Ω to 1MΩ (common values)",
      power: "1/4W",
      tolerance: "5%",
      organization: "Labeled compartments",
      type: "Carbon film",
    },
    tags: ["resistor", "components", "kit", "electronics"],
    relatedProducts: ["3", "12", "25"],
  },
  {
    id: "22",
    name: "3D Printed Drone Landing Gear",
    category: "3d-printed",
    subcategory: "Drone Parts",
    price: 34.99,
    currency: "USD",
    description: "Lightweight and durable landing gear for small to medium drones. Easy to install and replace.",
    longDescription: "Designed for FPV and hobby drones, this landing gear provides stable landing support while maintaining lightweight construction. Features quick-release mechanism for easy storage and transportation. Compatible with most 250-450mm frame sizes. Made from flexible TPU material to absorb landing shocks.",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    stock: 22,
    isInStock: true,
    isFeatured: false,
    isNew: true,
    rating: 4.4,
    reviewCount: 19,
    specifications: {
      material: "TPU (flexible)",
      frameCompatibility: "250-450mm",
      weight: "25g per set",
      color: "Black, White",
      printTime: "2 hours",
      mounting: "M3 screws (included)",
    },
    tags: ["drone", "landing", "gear", "fpv"],
    relatedProducts: ["1", "10", "26"],
  },
  {
    id: "23",
    name: "Laser Engraved Leather Wallet",
    category: "laser-engraved",
    subcategory: "Accessories",
    price: 49.99,
    currency: "USD",
    description: "Premium genuine leather wallet with custom laser engraved initials or design. Handcrafted quality.",
    longDescription: "Made from top-grain genuine leather, this bifold wallet features precise laser engraving for personalization. Includes multiple card slots, cash compartment, and ID window. The laser engraving creates a beautiful contrast against the leather. Perfect gift for special occasions or personal use.",
    images: [
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400",
    stock: 31,
    isInStock: true,
    isFeatured: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 62,
    specifications: {
      material: "Genuine Leather",
      style: "Bifold",
      cardSlots: "8 card slots + ID window",
      dimensions: "95mm x 85mm",
      customization: "Initials or custom design",
      finish: "Laser engraved, hand-stitched edges",
    },
    tags: ["wallet", "leather", "personalized", "gift"],
    relatedProducts: ["5", "20", "27"],
  },
  {
    id: "24",
    name: "Stepper Motor Driver Module (A4988)",
    category: "electronics",
    subcategory: "Drivers",
    price: 8.99,
    currency: "USD",
    description: "Precise stepper motor driver with microstepping capability. Perfect for CNC and 3D printer projects.",
    longDescription: "The A4988 stepper motor driver provides precise control over stepper motors with microstepping up to 16 steps. Features adjustable current limiting, overheat protection, and easy step/direction interface. Compatible with 3D printers, CNC machines, and automation projects. Requires external power supply.",
    images: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=400",
    stock: 55,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.5,
    reviewCount: 91,
    specifications: {
      voltage: "8V - 35V",
      current: "Up to 2A per coil",
      microstepping: "Up to 16 steps",
      interface: "Step/Direction",
      protection: "Overheat and overcurrent",
      compatibility: "Bipolar stepper motors",
    },
    tags: ["driver", "stepper", "motor", "cnc"],
    relatedProducts: ["15", "24", "28"],
  },
  {
    id: "25",
    name: "3D Printed Raspberry Pi Case with Fan",
    category: "3d-printed",
    subcategory: "Enclosures",
    price: 19.99,
    currency: "USD",
    description: "Protective case for Raspberry Pi with integrated cooling fan. Multiple models supported.",
    longDescription: "This ventilated case provides excellent protection and cooling for your Raspberry Pi. Features snap-fit design, access to all ports, and integrated 5V fan with speed control. Compatible with Raspberry Pi 3B+, 4B, and Zero W. Available in multiple colors. Keeps your Pi running cool even under heavy loads.",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    stock: 38,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.6,
    reviewCount: 84,
    specifications: {
      material: "PLA",
      compatibility: "Raspberry Pi 3B+, 4B, Zero W",
      fan: "5V, 40mm",
      color: "Black, White, Transparent",
      printTime: "3 hours",
      features: "Access to all ports, snap-fit design",
    },
    tags: ["raspberry", "pi", "case", "cooling"],
    relatedProducts: ["7", "13", "29"],
  },
  {
    id: "26",
    name: "Laser Engraved Phone Case - Wood Back",
    category: "laser-engraved",
    subcategory: "Phone Accessories",
    price: 39.99,
    currency: "USD",
    description: "Elegant phone case with real wood back panel and custom laser engraving. Multiple phone models.",
    longDescription: "This unique phone case combines modern protection with natural wood aesthetics. The back panel is made from real wood with custom laser engraving options. Provides full device protection while maintaining wireless charging compatibility. Available for popular iPhone and Samsung models.",
    images: [
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400",
    stock: 41,
    isInStock: true,
    isFeatured: true,
    isNew: true,
    rating: 4.7,
    reviewCount: 73,
    specifications: {
      material: "TPU frame + Wood back",
      compatibility: "iPhone 12-15, Samsung S21-S24",
      protection: "Drop protection, corner reinforcement",
      wirelessCharging: "Compatible",
      woodType: "Walnut, Bamboo, Cherry",
      customization: "Laser engraved design or text",
    },
    tags: ["phone", "case", "wood", "custom"],
    relatedProducts: ["4", "17", "30"],
  },
  {
    id: "27",
    name: "LED Strip RGB (1m) - WS2812B",
    category: "electronics",
    subcategory: "LEDs",
    price: 16.99,
    currency: "USD",
    description: "Addressable RGB LED strip with individually controllable LEDs. Perfect for lighting projects.",
    longDescription: "This 1-meter WS2812B LED strip features 60 individually addressable RGB LEDs. Each LED can be controlled independently for stunning lighting effects. Compatible with Arduino, Raspberry Pi, and ESP32. Includes weatherproof coating option. Perfect for home automation, art installations, and display projects.",
    images: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=400",
    stock: 67,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.8,
    reviewCount: 145,
    specifications: {
      length: "1 meter",
      leds: "60 addressable LEDs",
      voltage: "5V",
      current: "60mA per LED (max)",
      protocol: "WS2812B (NeoPixel compatible)",
      waterproof: "IP65 option available",
      compatibility: "Arduino, Raspberry Pi, ESP32",
    },
    tags: ["led", "rgb", "strip", "addressable"],
    relatedProducts: ["3", "12", "21"],
  },
  {
    id: "28",
    name: "3D Printed Tool Holder Organizer",
    category: "3d-printed",
    subcategory: "Organizers",
    price: 27.99,
    currency: "USD",
    description: "Wall-mountable tool holder with slots for screwdrivers, pliers, and small tools. Customizable design.",
    longDescription: "Keep your workshop organized with this wall-mountable tool holder. Features multiple slots sized for common tools like screwdrivers, pliers, wrenches, and hex keys. Includes mounting holes for easy wall installation. Modular design allows for expansion. Made from durable PLA+ material.",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    stock: 33,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.4,
    reviewCount: 27,
    specifications: {
      material: "PLA+",
      dimensions: "300mm x 150mm x 50mm",
      slots: "10 tool slots",
      mounting: "Wall mount with screws",
      color: "Black, Gray",
      printTime: "4 hours",
    },
    tags: ["tool", "holder", "workshop", "organizer"],
    relatedProducts: ["7", "19", "25"],
  },
  {
    id: "29",
    name: "Laser Engraved Cutting Board - Custom Design",
    category: "laser-engraved",
    subcategory: "Kitchen",
    price: 54.99,
    currency: "USD",
    description: "Premium bamboo cutting board with custom laser engraved design. Functional and beautiful.",
    longDescription: "This eco-friendly bamboo cutting board features custom laser engraved patterns or text. The engraving is food-safe and won't fade with use. Perfect for serving cheese, bread, or as a decorative kitchen accessory. Bamboo is naturally antimicrobial and more sustainable than plastic. Makes an excellent gift.",
    images: [
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400",
    stock: 24,
    isInStock: true,
    isFeatured: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 58,
    specifications: {
      material: "Bamboo",
      dimensions: "Small (25x18cm), Medium (35x25cm), Large (45x30cm)",
      thickness: "12mm",
      finish: "Food-safe oil finish",
      customization: "Custom design or text",
      care: "Hand wash, re-oil monthly",
    },
    tags: ["cutting", "board", "bamboo", "kitchen", "gift"],
    relatedProducts: ["8", "14", "29"],
  },
  {
    id: "30",
    name: "Battery Holder - AA/AAA (4x)",
    category: "electronics",
    subcategory: "Components",
    price: 4.99,
    currency: "USD",
    description: "Plastic battery holder for 4x AA or AAA batteries. Convenient for portable electronics projects.",
    longDescription: "This simple but essential component holds 4 AA or AAA batteries in series configuration. Features wire leads for easy connection to your projects. Secure battery retention and durable plastic construction. Perfect for portable electronics, robot projects, and power supply applications.",
    images: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=800",
    ],
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4f18f48?w=400",
    stock: 95,
    isInStock: true,
    isFeatured: false,
    isNew: false,
    rating: 4.3,
    reviewCount: 167,
    specifications: {
      capacity: "4 batteries",
      type: "AA or AAA",
      configuration: "Series",
      voltage: "6V (AA) or 4.8V (AAA)",
      leads: "Wire leads included",
      material: "ABS plastic",
    },
    tags: ["battery", "holder", "power", "portable"],
    relatedProducts: ["3", "15", "21"],
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.description.toLowerCase().includes(lowerQuery) ||
      p.tags.some((tag) => tag.toLowerCase().includes(lowerQuery))
  );
}

